### ISSUE TITLE
Feedback Session 2

### ISSUE THREAD

**Issue by firasm** [ubco-W2022T2-data301/project-group-group18#2]
## Feedback for Group

1. What is your contracted grade?

- A+

2. Are there are any group dynamics issues that we need to be aware of ? 

- No

3. Notes from [Islam/Saira] on Feedback on the analysis:

- [x] Move `project_functions` inside a subdirectory, rename `code` to `scripts`
- [x] Update jupyter notebooks to import functions correctly
- [x] Update ticklabels so they are note sideways, and show only 4-5 instead of one every year
- [x] Countries should all be on the y-axis
- [x] `analysis1` has a fair bit of work to do (insightful commentary, research questions in more depth, explain what the plots are showing, do "more" with the data). **Feel free to add research questions**
- [x] Remove "regions" label
- [x] Replace box plots with Ridgeline plots (violin plots are also a possibility)
- [x] Turn this all into a compound plot -- [use this](https://dev.to/thalesbruno/subplotting-with-matplotlib-and-seaborn-5ei8)
- [x] Add a table that shows proportions
- [x] Add insightful commentary
- [x] analysis3 - reset the index
- [x] Remove 'region"
- [x] Add "SupTitle" to all the plots 
- [x] Make the Ridgeline plot "taller"
- [x] Another plot of distribution of literacy rates NOT split by gender (keep the gender one)
- [x] Flip x-y axis for wealth and gender
- [x] Combine wrangling in a method chain

**Comment by dabby04** [comment]
All corrections done to aim for an A+
