### ISSUE TITLE
MS4 Feedback

### ISSUE THREAD

**Issue by sairafurqan** [ubco-W2022T2-data301/project-group-group18#4]
## Feedback for Group 18

Please see Dr. Firas after class or drop by one of the TA office hours.

1. Notes from [Saira] on Feedback on the analysis:

- I don't see much work or complex visualizations done.
- [x] Add Conclusion in each of the notebooks

## Contracted Grade

1. What is your contracted grade?

- A+

2. Are you on track to satisfy all the requirements of your contracted grade?

- No, you should consider contracting for a lower grade to ensure you meet a high-level quality on all the work you submit. [Please review the details of each contracted grade here](https://firas.moosvi.com/courses/data301/2022_WT2/project/introduction.html) and if you have questions, come see the instructor or the Project TAs for more details.

**Comment by dabby04** [comment]
@firasm - could you help with this?

**Comment by firasm** [comment]
Hello, I looked through the analysis notebooks, and @julieflament and @dabby04 's notebooks look fine, but @aaravg31 I think you have a bit more work to do to achieve all the elements of an A+ contracted grade. 

For example:
- [ ] not all of the subquestions have been answered, 
- [ ] plot titles and labels aren't appropriately set, 
- [ ] there aren't enough complex visualizations in your analysis (for e.g., no distribution plots)

**Comment by firasm** [comment]
- [x] Actually one other thing : all of you are missing an EDA section but I remember seeing it before. Could you add that back in please ?

**Comment by dabby04** [comment]
Issues resolved!
